---
- name: Collect Server Details
  hosts: instance-2
  become: true
  tasks:
    - name: Collect CPU, Memory, Storage, Open files, list, Syslog of server
      command: |
        echo "CPU usage: $(top -bn 1 | awk '/^%Cpu/ {print $2}')"
        echo "--------------------------------------------------"

        echo "Memory usage: $(free -m | awk '/^Mem:/ {print int($3/$2 * 100)}')"
        echo "--------------------------------------------------"

        echo "Storage: $(df -h / | awk '/\// {print $5}')"
        echo "-------------------------------------------------"

        echo "Open files count: $(lsof | wc -l)"
        echo "------------------------------------------------"

        echo "Process list: $(ps aux)"
        echo "------------------------------------------------"

        echo "Syslogs: $(cat /var/log/syslog /var/log/messages /var/log/auth.log 2>/dev/null | tail -n 4)"
      register: server_details

    - name: Save the details in CSV file
      copy:
        content: "{{ server_details.stdout_lines | join('\n') }}"
        dest: "/opt/details.csv"
       
